### ISSUE TITLE
Allow editing source code of the file

### ISSUE THREAD

**Issue by dlippok** [dlippok/photometric-viewer#143]
The user should be able to edit the source text of the photometric file. Whenever the source code has changed, the UI should be reloaded to reflect the data in the text editor.

The user should be able to save the opened file in the same format as it was opened. The saving should be independent from the export function which should allow the user to convert between opened formats.

## ToDos

- [x] Enable editing file source and reload preview when going back
- [x] Enable saving content to a file
- [x] Enable creating new empty files
- [x] Allow opening new window to create new file if another file has already been opened
- [x] Warn about unsaved changes when closing the window without saving recent changes
